services:
  bitcoin-node:
    image: bitcoin-core:${osName}-${osRelease}-bitcoin-${bitcoinCoreVersion}  
    container_name: bitcoin-core
    volumes:
      - ${containerVolume}:/bitcoin-data
    ports:
      - "${p2pPort}:8333"
      - "${rpcPort}:8332"
    restart: unless-stopped
    user: "1000:1000"