services:
  bitcoin-node:
    image: ${imageName}:${osName}-${osRelease}-bitcoin-${bitcionCoreVersion}  
    container_name: ${containerName}
    volumes:
      - ${containerVolume}:/bitcoin-data
    ports:
      - "${p2pPort}:8333"
      - "${rpcPort}:8332"
    restart: unless-stopped
    user: "1000:1000"